### ISSUE TITLE
Intellij Build fails

### ISSUE THREAD

**Issue by sayas01** [osmlab/atlas#420]
All the CompleteObjects classes throw "Class is not abstract and does not override" error in Intellij. Gradle build is successful but cannot build the project in Intellij. Following is the screenshot of the error message for CompletePoint class.
![image](https://user-images.githubusercontent.com/42149840/56391200-d2e16200-61e2-11e9-97fa-80dcb6f0a78a.png)

![image](https://user-images.githubusercontent.com/42149840/56391464-8e09fb00-61e3-11e9-915f-3b770672afdb.png)

**Comment by sayas01** [comment]
@lucaspcram @yazad3 Could https://github.com/osmlab/atlas/pull/424 also include fixes for this issue?

**Comment by yazad3** [comment]
@sayas01 - the build is failing because you have not enabled annotation processing. This is now required for the [Lombok](https://projectlombok.org/) dependency that has been added in Atlas.

Please "check mark" the highlighted option (Enable annotation processing) under Preferences | Build, Execution, Deployment | Compiler | Annotation Processors.

<img width="1293" alt="AnnotationProcessing" src="https://user-images.githubusercontent.com/1376056/56684460-a74bf500-6684-11e9-85ef-8128b46d21dd.png">

**Comment by sayas01** [comment]
@yazad3 I had enabled it based on your PR description https://github.com/osmlab/atlas/pull/412. Looks like I had to install Lombok plugin and restart Intellij to build successfully. Thank you for the response!

**Comment by yazad3** [comment]
@sayas01 - the plugin is needed for Eclipse but not for IntelliJ, IMO. But glad its working now.

Cheers,
